version: "3.2"

services:
  vote:
    build: ./vote
    # use python rather than gunicorn for local dev
    command: python app.py
    depends_on:
      redis:
        condition: service_healthy
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: dockersamples/examplevotingapp_result:dotnet-nanoserver-1809
    build:
      context: ./result/dotnet
      dockerfile: Dockerfile.1809
    ports:
      - "5001:80"
    environment:
      - "ConnectionStrings:ResultData=Server=db;Port=4000;Database=votes;User=root;SslMode=None"
    depends_on:
      - db

  worker:
    image: dockersamples/examplevotingapp_worker:dotnet-nanoserver-1809
    build:
      context: ./worker/dotnet
      dockerfile: Dockerfile.1809
    environment:
      - "ConnectionStrings:VoteData=Server=db;Port=4000;Database=votes;User=root;SslMode=None"
    depends_on:
      - message-queue
      - db

  message-queue:
    image: nats:2.0.4

  db:
    image: dockersamples/tidb:nanoserver-1809
    ports:
      - "3306:4000"

networks:
  default:
    external:
      name: nat
